// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7whqEOi4stDOTJPamOJMf769REApM2xs',
    appId: '1:1034162289688:web:ef3272558c4f0a469d576d',
    messagingSenderId: '1034162289688',
    projectId: 'my-anyself-project',
    authDomain: 'my-anyself-project.firebaseapp.com',
    storageBucket: 'my-anyself-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyYMG8EwbJnyYWtRqV1FigXzhe8F3MK9M',
    appId: '1:1034162289688:android:3f01f2163e1dc5a59d576d',
    messagingSenderId: '1034162289688',
    projectId: 'my-anyself-project',
    storageBucket: 'my-anyself-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-PPQ8yHQdfJpM1YrlL6J4ij1d1x-Aw2w',
    appId: '1:1034162289688:ios:df763281f87fe9799d576d',
    messagingSenderId: '1034162289688',
    projectId: 'my-anyself-project',
    storageBucket: 'my-anyself-project.appspot.com',
    iosBundleId: 'com.codelooms.analytics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-PPQ8yHQdfJpM1YrlL6J4ij1d1x-Aw2w',
    appId: '1:1034162289688:ios:df763281f87fe9799d576d',
    messagingSenderId: '1034162289688',
    projectId: 'my-anyself-project',
    storageBucket: 'my-anyself-project.appspot.com',
    iosBundleId: 'com.codelooms.analytics',
  );
}
