// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHZ3fYS2FhohcM8re-0wwJDoeTccJpJZ8',
    appId: '1:932443134331:web:f72cd5ce0eb5572b6445de',
    messagingSenderId: '932443134331',
    projectId: 'my-horlicks-projects',
    authDomain: 'my-horlicks-projects.firebaseapp.com',
    storageBucket: 'my-horlicks-projects.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7-z0jrrBxnESFTRYmTM1OCvi0FSP_qvc',
    appId: '1:932443134331:android:4e56461b85cd79066445de',
    messagingSenderId: '932443134331',
    projectId: 'my-horlicks-projects',
    storageBucket: 'my-horlicks-projects.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWNMeOn2hShhWtYH8elfSgPXOPkZmeEiE',
    appId: '1:932443134331:ios:a19e858bc78d58766445de',
    messagingSenderId: '932443134331',
    projectId: 'my-horlicks-projects',
    storageBucket: 'my-horlicks-projects.appspot.com',
    iosBundleId: 'com.codelooms.analyticsIntegration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWNMeOn2hShhWtYH8elfSgPXOPkZmeEiE',
    appId: '1:932443134331:ios:a19e858bc78d58766445de',
    messagingSenderId: '932443134331',
    projectId: 'my-horlicks-projects',
    storageBucket: 'my-horlicks-projects.appspot.com',
    iosBundleId: 'com.codelooms.analyticsIntegration',
  );
}
