// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC29J5nnwJxrF_NbaFOeQd8IEOY77xhKaE',
    appId: '1:29541564075:web:9c02644c5faec36e3641ee',
    messagingSenderId: '29541564075',
    projectId: 'my-amob-project',
    authDomain: 'my-amob-project.firebaseapp.com',
    storageBucket: 'my-amob-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC49nCowd8vm53zPWFHIwUgx7AdRV2g5Mk',
    appId: '1:29541564075:android:67b44e500a33bb993641ee',
    messagingSenderId: '29541564075',
    projectId: 'my-amob-project',
    storageBucket: 'my-amob-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk5J1UAfbkc4lsmTjjyEX2yYtbpYKXDPo',
    appId: '1:29541564075:ios:78cc572aac74e21b3641ee',
    messagingSenderId: '29541564075',
    projectId: 'my-amob-project',
    storageBucket: 'my-amob-project.appspot.com',
    iosBundleId: 'com.codelooms.admob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk5J1UAfbkc4lsmTjjyEX2yYtbpYKXDPo',
    appId: '1:29541564075:ios:78cc572aac74e21b3641ee',
    messagingSenderId: '29541564075',
    projectId: 'my-amob-project',
    storageBucket: 'my-amob-project.appspot.com',
    iosBundleId: 'com.codelooms.admob',
  );

}