// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5KkM0rSLIGi0jxaRZXnlaaH3BNb_ktSY',
    appId: '1:1025081132596:web:1b4d16786e453ab43c2c61',
    messagingSenderId: '1025081132596',
    projectId: 'authfb',
    authDomain: 'authfb-44a79.firebaseapp.com',
    storageBucket: 'authfb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFvwaPs4THfrVTu3a6pptAFTiDEyZTTEA',
    appId: '1:1025081132596:android:928214e9cd17c6303c2c61',
    messagingSenderId: '1025081132596',
    projectId: 'authfb',
    storageBucket: 'authfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA14aKPbOro1SgmMHvTxPd-3MiZRJql0Q',
    appId: '1:1025081132596:ios:6076f38a413bf6143c2c61',
    messagingSenderId: '1025081132596',
    projectId: 'authfb',
    storageBucket: 'authfb.appspot.com',
    iosBundleId: 'com.codelooms.fbauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA14aKPbOro1SgmMHvTxPd-3MiZRJql0Q',
    appId: '1:1025081132596:ios:6076f38a413bf6143c2c61',
    messagingSenderId: '1025081132596',
    projectId: 'authfb',
    storageBucket: 'authfb.appspot.com',
    iosBundleId: 'com.codelooms.fbauth',
  );
}
