// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJjkpYHXzomBFDRdrk1pXOkoLesNm8jMM',
    appId: '1:106881328405:web:c03a3b6dec72dc2e36751c',
    messagingSenderId: '106881328405',
    projectId: 'my-dil-push-notify',
    authDomain: 'my-dil-push-notify.firebaseapp.com',
    storageBucket: 'my-dil-push-notify.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7bh7aGstLsNL4S-17Xr0SJf3zmyCJvIY',
    appId: '1:106881328405:android:27a12cfa7eea7b4536751c',
    messagingSenderId: '106881328405',
    projectId: 'my-dil-push-notify',
    storageBucket: 'my-dil-push-notify.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU6MZpRi99560zR8F9iiF5kZFrrMzLMvo',
    appId: '1:106881328405:ios:2bfbc67c6ed0cdde36751c',
    messagingSenderId: '106881328405',
    projectId: 'my-dil-push-notify',
    storageBucket: 'my-dil-push-notify.appspot.com',
    iosBundleId: 'com.codelooms.pushNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU6MZpRi99560zR8F9iiF5kZFrrMzLMvo',
    appId: '1:106881328405:ios:2bfbc67c6ed0cdde36751c',
    messagingSenderId: '106881328405',
    projectId: 'my-dil-push-notify',
    storageBucket: 'my-dil-push-notify.appspot.com',
    iosBundleId: 'com.codelooms.pushNotifications',
  );
}
